// Code generated by pkg/codegen/config/main.go. DO NOT EDIT.
// Package buildconfig contains a set of exported constants that represent configuration variables of Rancher at build-time.
package buildconfig

const (
	CspAdapterMinVersion = "103.0.0+up3.0.0"
	DefaultShellVersion  = "vardhaman123/shell:v0.2.1"
	FleetVersion         = "104.0.0+up0.10.0-rc.14"
	WebhookVersion       = "104.0.0+up0.5.0-rc8"
)
